-keep class org.videolan.libvlc.** { *; }
-keep class org.videolan.libvlc.interfaces.** { *; }
-keep interface org.videolan.libvlc.interfaces.** { *; }
-keep class org.videolan.medialibrary.** { *; }
